projectId: "<PROJECT_ID>"
region: "us-central1"
service:
  name: "oc-backend-service"
  accountEmail: "cloud-run-sa@<PROJECT_ID>.iam.gserviceaccount.com"
  allowUnauthenticated: true
  ingress: "all" # all | internal | internal-and-cloud-load-balancing
  timeoutSeconds: 300
  concurrency: 80
  minInstances: 0
  maxInstances: 2
  cpu: 1
  memory: "512Mi"
  vpcAccess:
    connector: "projects/<PROJECT_ID>/locations/us-central1/connectors/<CONNECTOR_NAME>"
    egress: "all-traffic" # all-traffic | private-ranges-only
  env:
    - name: "NODE_ENV"
      value: "production"
    - name: "DB_HOST"
      secret:
        name: "db-host"
        version: "latest"
        projectId: "<PROJECT_ID>"
    - name: "DB_PASSWORD"
      secret:
        name: "db-password"
        version: "latest"
        projectId: "<PROJECT_ID>"
image:
  repository: "us-central1-docker.pkg.dev/<PROJECT_ID>/backend-docker/oc-backend-service"
  tag: "latest"
